= Creating static environments

You can create static environments within your current workspace and use them to internally deploy and test your applications. 

.*Prerequisites*

* You successfully signed in to Stonesoup.


.*Procedures*

. In the console, select *Settings*.
. Select *Static environment* and then select *Next*.
. In the *Environment name* field, enter the name of the environment that you want to create, for example, "Development-environment".
. From the *Deployment strategy* drop-down list, select either *Automatic* or *Manual*.

+
NOTE: The deployment strategy handles any changes that you make to your code. If you select *Manual*, you must manually promote any new component updates to the environment. If you select *Automatic*, Stonesoup automatically deploys new component updates to the environment. You can change the deployment strategy when you promote new component updates.

. From the *Order in continuous delivery* drop-down list, select an option that will be the default for your application. 

+
NOTE:  *Order in continuous delivery* determines the progression of environments that your application is deployed to after it passes all integration tests, starting at 0.

. From the *Environment type* drop-down list, select an environment type.

. From the *Location* drop-down list, select the location where you want to deploy and test your application. 

. Select *Create environment*.

.*Verification*
After you successfully create an environment, the system displays the environment in the following places:

* *Settings > Environments* 
* *Applications > Environment* 
