= Upgrading the build pipeline

By default, {ProductName} builds the components of your applications using, as the name suggests, the default build pipeline. This pipeline offers quick and easy containerized deployment. It also secures your supply chain, by conforming to the specification for SLSA Build Level 3.

However, there are three reasons you might want to upgrade your build pipeline to a custom build:

* Customize: Upgrading the build pipeline enables you to tailor the build process that {ProductName} uses for the components of your application, to better meet your specific needs.
* Reinforce security: When you upgrade, {ProductName} adds a variety of security checks and scans on your pipeline that get run on each build.  
* Continuous integration: Upgraded build pipelines automatically rebuild your components every time a new commit is merged into the main branch of their repositories.

.Prerequisites

* You must have an application that {ProductName} has successfully built and deployed using the default build pipeline.  

.Procedure

To upgrade the build pipeline:

. In the *Overview* tab of your application, scroll down and select *Manage build pipelines*.
. If you have not already installed the {ProductName} GitHub application, select Install GitHub application on the “Manage build pipelines” popup page. 

+
[NOTE]
====
If you want to restrict the GitHub application’s access to certain repositories only, use the Only select repositories option in GitHub during the installation.
====

. Returning to the “Manage build pipelines” page in {ProductName}, for any component whose build pipeline you would like to upgrade, select *Send pull request*.  
. Select *Merge in GitHub*.
. In GitHub, merge the pull request from the “red-hat-trusted-app-pipeline” bot.
. Let {ProductName} complete another PipelineRun for the newly-upgraded build pipeline.
 
.Verification

Confirm that most of the build pipeline tasks that {ProductName} previously skipped are now included in the recent PipelineRun: 

. Go to *Activity > Pipeline runs*. 
. Select the most recent *PipelineRun*. 
. View the build pipeline tasks and scroll down to view the vulnerabilities scan, which summarizes the results of the `clair-scan`. 

.Updates

If you upgrade your build pipeline for a component, then whenever we release a new `build-definition` for upgraded pipelines, the {ProductName} bot submits a pull request (PR) to the git repository of your component. These PRs only change the `.tekton` directory of the component repository; they do not alter the source code specific to your component in any way.

When you see a PR from the {ProductName} bot, please merge it to keep your pipeline updated. If you do not merge these PRs, {ProductName} might not be able to build or test your components correctly.

.Customization

After upgrading the build pipeline, you can also customize it: 

. Upgrade the build pipeline of your component, as previously described. 
. Go to the component’s GitHub repository. 
. Find the new `.tekton` directory, which is the result of upgrading the build pipeline. 
. Modify the contents of this directory to change how {ProductName} builds the component. 

[NOTE]
====
{ProductName} creates pull requests that contain updates to the pipeline definitions under the `.tekton` directory.
Run the tests on these pull requests by creating a comment containing `/ok-to-test` and then merging the changes when the tests pass.
====

.Security
To reinforce the security of your custom build pipeline, complete the following steps:

* Add an `OWNERS` file to the `.tekton` directory and list trusted contributors there.
** To learn more, see Kubernetes docs about link:https://www.kubernetes.dev/docs/guide/owners/[OWNERS files].
* Avoid commenting `/ok-to-test` on pull requests from untrusted authors, review such PRs carefully first. The `/ok-to-test` comment runs the PipelineRun, and malicious code in a PR can change your build and compromise the security of your application.
** To learn more about running the PipelineRun, see the link:https://pipelinesascode.com/docs/guide/running/#running-the-pipelinerun[Running the PipelineRun guide] from Pipelines as Code docs. 
* Specify the PipelineRun definition source by setting the `pipelinerun_provenance` setting to `default_branch`. This way Pipelines as Code uses the PipelineRun definition from the default branch of the repository, and only contributors with default branch merge rights have access to PipelineRun.
+
If you don’t set `pipelinerun_provenance`, you allow the default behaviour: the PipelineRun definition is fetched from a branch where the PipelineRun event is triggered. This way bad actors can change the PipelineRun definition and get access to your code.

** To learn more about setting the PipelineRun definition source, see link:https://pipelinesascode.com/docs/guide/repositorycrd/#pipelinerun-definition-provenance[PipelineRun definition provenance].
