= Releasing with an advisory

In order to be able to create an advisory when releasing a Snapshot, certain data has to be included in the Release Plan Admission.

.*Prerequisites*

* You have an existing Release Plan Admission for your release.

.*Procedures*

. Add the advisory data in your ReleasePlanAdmission object.

*Example `ReleasePlanAdmission.yaml` object*

[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  ..
spec:
 data:
   releaseNotes: <advisory data> <.>
----
<.> Advisory data to be included.

.*UMB messages*

When an advisory yaml is created and pushed to the advisories Gitlab repo, a message is sent automatically to UMB (Universal Message Bus) via Gitlab CI.
The message is sent to topic VirtualTopic.eng.konflux.advisory.

The advisory yaml is converted to json and included as the message body.

.*Advisory timestamps*

Each advisory will be populated with a ship_date and updated_date in its metadata.

*Example `advisory.yaml`*

[source,yaml]
----
apiVersion: rhtap.redhat.com/v1alpha1
kind: Advisory
metadata:
  name: 2023:000004
  ship_date: 2024-03-11T13:23:07Z <.>
  updated_date: 2024-03-11T13:23:07Z <.>
spec:
  ..
----
<.> Ship date in ISO 8601 format.
<.> Updated date in ISO 8601 format. Will be the same as ship_date initially.

When an advisory is updated via a merge request at a later point, the ship_date
is required to be updated.
