= Managed services team onboarding
When an application is ready for release, the Development team contacts the Managed Environment team. For example, their organization's SRE team requested access to the Managed Environment for the first production release. 

The Managed Environment team creates the following objects on the Managed workspace:

* *ReleasePlanAdmission* - The Managed Environment team creates or updates the `ReleasePlanAdmission` object in response to the `ReleasePlan` object created by the development team. It indicates that the Managed Environment team has approved the application specified in the link:https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/proc_release_plan/[ReleasePlan] object.

* *`copy-application.sh`* - The Managed Environment team runs the `copy-application.sh` script by defining the application name before releasing an application to production. The script copies the application and all of its components from the Development to the Managed workspace. As a result, when releasing an application to production, the Managed Environment team uses the application on its workspace rather than the one on the Developer workspace.
Additionally, if the Development team adds a new component to the application on their workspace,  they must notify the Managed Environment team. So they can run the `copy-application.sh` script again to ensure that the managed workspace has the most recent version of the application.

== Creating a `ReleasePlanAdmission` object

.*Prerequisites*

* An existing Development and Managed workspace.

* An existing `ReleasePlan` object in the Development workspace.

.*Procedures*

. Create a `ReleasePlanAdmission.yaml` object locally.

+
*Example `ReleasePlanAdmission.yaml` object*

+
[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
 name: sre-production <.>
 namespace: managed-workspace <.>
spec:
 applications:
  - demo-app <.>
 data: <key> <.>
 environment: <sre-production> <.>
 origin: <dev-workspace> <.>
 pipelineRef: <pipeline_ref> <.>
 policy: <policy> <.>
 serviceAccount: <service-account> <.>

----

+
<.> The name of the release plan admission.
<.> The Managed environment team's workspace.
<.> A list of applications that you want to enable to be deployed in the managed workspace.
<.> Optional: An unstructured key used for providing data for the managed Pipeline.
<.> Optional: The environment from which the application updates are allowed to be received in the Managed workspace. This environment is created by the Development team.
<.> The development team workspace where the application is defined.
<.> Reference to the Pipeline to be executed by the release service.
<.> The enterprise contract policy against which the system validates an application before releasing it to production.
<.> Optional: The name of the service account to use in the Pipeline to gain elevated privileges. It's used only if you have defined the `pipelineRef` value.

+
NOTE: The  ReleasePlanAdmission.yaml represents the reciprocal link to the ReleasePlan.yaml objects created by the development team.

. In the Managed workspace, apply the `ReleasePlanAdmission.yaml` file and add the resource to your cluster by running the following command:

+
[source,shell]
----
oc apply -f ReleasePlanAdmission.yaml -n managed
----

.*Verification*

. On the Trusted Application Pipeline console, select the *Release services* > *Release plan admission* tab.
. Review the Release plan admission object that you just added. Using the Release plan admission tab, you can update or delete the selected Release plan object.

 
== The `copy-application.sh` script

.*Prerequisites*

* An existing Development and Managed workspace.

* Download link:https://github.com/redhat-appstudio/release-service-utils/blob/main/copy-application.sh[./copy-application.sh] script.

.*Procedures*

* Run the following command to copy the application from the development workspace to the managed workspace:

+
[source,shell]
----
./copy-application.sh <managed workspace name> -a <development workspace name>/<application name>
----

+
To show the command usage information, run the `./copy-application.sh --help` command.
