= SBOMs

:toc: left
:icons: font
:numbered:
:source-highlighter: highlightjs

== Software bill of materials
A software bill of materials (SBOM) provides greater transparency for your software supply chain. In {ProductName}, an SBOM is a list of all the software libraries that a xref:../glossary/index.adoc#_component[component] uses. Those libraries might enable specific functionality, facilitate development, or serve some other purpose. 

You can use an SBOM to better understand the composition of your software, identify vulnerabilities, and assess the potential impact of any security issues that might arise. You might also need to provide your customers with an SBOM to comply with cybersecurity regulations. 

== Downloading an SBOM

*Prerequisites*

* Install the link:https://docs.sigstore.dev/cosign/installation/[Cosign] CLI tool.

* Install the link:https://stedolan.github.io/jq/download/[jq] CLI tool.

* xref:cli/getting_started_in_cli.adoc[Login] to {ProductName}.

*Procedure*

. List your components.
+
[source]
----
$ oc get components
----
+
.Example output

+
[source]
----
NAME                               AGE   STATUS   REASON   TYPE
devfile-sample-go-basic-8wqt       8m54s True     OK       Updated
devfile-sample-python-basic-ikch   20d   True     OK       Updated
----

. Choose which component's SBOM you want to download. Then use `oc get` and the jq CLI tool to get the component image path.

+
[source]
----
$ oc get component <component name> -ojson | jq '.status.containerImage'
----

+
.Example

+
[source]
----
$ oc get component devfile-sample-python-basic-ikch -ojson | jq '.status.containerImage'
    "quay.io/redhat-appstudio/user-workload@sha256:<output omitted>"
----

. Use Cosign to download the SBOM. From the output of the last command, pass the image path as an argument into Cosign's `download sbom` command. Be sure to delete any quotation marks around the image path.

+
.Example
+
[source]
----
$ cosign download sbom quay.io/redhat-appstudio/user-workload@sha256:<output omitted>
----

+
.. Because  the SBOM is unsigned, Cosign displays a warning about its authenticity. You can still use this SBOM for standard business processes, like providing an SBOM to your customers. 
+
[IMPORTANT]
====
Do not use this unsigned SBOM as a legal document. 
====
+
[source]
----  
WARNING: Downloading SBOMs this way does not ensure its authenticity. 
If you want to ensure a tamper-proof SBOM, download it using 'cosign download attestation <image uri>' 
or verify its signature using 'cosign verify --key <key path> --attachment sbom <image uri>'.
----

+
.. (Optional) To view the full SBOM in a searchable format, you can redirect the output:

+
[source]
----  
$ cosign download sbom quay.io/redhat-appstudio/user-workload@sha256:<output omitted> > sbom.txt
----

== Reading the SBOM
In any SBOM, you can find the following information about each library the component uses:

. Author or publisher
. Name
. Version
. Licenses

You can use this information to verify that each library is safely sourced, updated, and compliant.

Example SBOM

[source]
----
{
    "bomFormat": "CycloneDX",
    "specVersion": "1.4",
    "serialNumber": "urn:uuid:89146fc4-342f-496b-9cc9-07a6a1554220",
    "version": 1,
    "metadata": {
        ...
    },
    "components": [
        {
            "bom-ref": "pkg:pypi/flask@2.1.0?package-id=d6ad7ed5aac04a8",
            "type": "library",
            "author": "Armin Ronacher <armin.ronacher@active-4.com>", <1>
            "name": "Flask", <2>
            "version": "2.1.0", <3>
            "licenses": [ <4>
                {
                    "license": {
                        "id": "BSD-3-Clause"
                    }
                }
            ],
            "cpe": "cpe:2.3:a:armin-ronacher:python-Flask:2.1.0:*:*:*:*:*:*:*",
            "purl": "pkg:pypi/Flask@2.1.0",
            "properties": [
                {
                    "name": "syft:package:foundBy",
                    "value": "python-package-cataloger"
                    ...
----

== Additional resources
* xref:../how-to-guides/webui-sbom.adoc[SBOMs in the web UI]
