= Build Pipeline customization

You can update and manage the Build Pipelines for each component in your application.

NOTE: {ProductName} leverages the xref:concepts/pipelines/index.adoc[pipeline services] to build images.

.Prerequisites

* You have access to a Git repository that follows xref:concepts/pipelines/index.adoc#_pipeline_as_code[Pipelines as Code].

* The Git repository has a build _PipelineRun_ template in the `.tekton` directory.

* The build <<_pipelinerun_template>> follows the annotations used by Pipelines as Code.


== Customizing the Build Pipeline

.Procedure

* Update the `.yml` files in your `\{source_repository} > .tekton` directory for appropriate _PipelineRun_ definitions. The `.tekton` directory can have many .yml files, for example, `push.yml` or `pull.yml`. The following example displays a _PipelineRun_ to run the `build-service-on-push` pipeline:
+
----
apiVersion: tekton.dev/v1beta1 <1>
kind: PipelineRun <2>
metadata:
    name: build-service-on-push <3>
    annotations: <4>
        pipelinesascode.tekton.dev/on-event: "[push]"
        pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
    params: <5>
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: 'quay.io/redhat-appstudio/user-workload:{{revision}}'
    pipelineSpec:
      finally:
      - name: show-summary <6>
        params:
        - name: pipeline-run-name
          value: $(context.pipelineRun.name)
        - name: git-url
          value: $(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)
        - name: image-url
          value: $(params.output-image)
workspaces: <7>
        - name: workspace
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
status: {}
----

+
<1> PipelineRun API version v1beta1.
<2> Specifies the type of Kubernetes object. In this example, _PipelineRun_.
<3> Unique name to identify this PipelineRun.
<4> Definitions of tasks that the system runs. 
<5> Specifies the list of parameters required to run the Pipeline.
<6> Name of the Pipeline that the system runs.
<7> Workspace used by the PipelineRun.

== _PipelineRun_ template

To create a build PR, the `{_PipelineRun_ template}.yml` file in the `\{source_repository} > .tekton` directory must include:

* Params
* Workspace
* Annotations
* pipelineSpec

=== Params

Every supported Tekton Pipeline resource should populate any of the following user-defined params as part of their build execution in a _PipelineRun_:

* git-url

* git-revision

* output-image

* dockerfile-path

* path-context

=== Annotations

Annotations are additional, informative tags. A tag allows you to classify or group various objects to ensure that you can easily watch them after an execution. The values of annotations do not change during runtime because they are static.

To customize a build pipeline, you need to set the `on-event` and `on-target-branch` annotations.

NOTE: link:https://pipelinesascode.com[Pipelines as Code] adds annotations automatically when it creates the PipelineRun object on OpenShift.

=== Workspaces

Workspaces declare shared storage volumes that a xref:glossary/index.adoc#_task[Task] in a Pipeline needs at runtime to receive input or provide output.

=== pipelineSpec

In pipelineSpec, you can see each Task of a PipelineRun. You can also use pipelineSpec to add, update, and delete Tasks.
