= Get started

////
CP Development Team <cp-devel@redhat.com>
:toc: left
:icons: font
:numbered:
:source-highlighter: highlightjs

== Scope
Learn how a project team can onboard a product to {ProductName}. 

== Onboarding to {ProductName}

{ProductName} meets the needs of different Red Hat products. It uses many Red Hat services needed for building and releasing products to an appropriate environment.

*Prerequisites*

* Administrator creates a tenant xref:glossary/index.adoc#_workspace[workspace].

* The administrator then invites a developer to this workspace.

*Procedures*

Complete the following steps to onboard a project to {ProductName}:

. Create an application
.. Add components
.. Configure components
.. Configure xref:getting-started/build_service.adoc[Build Pipeline] for the components

+
NOTE: Your components are not fully configured until you browse to GitHub and merge a pull request (PR) for each component to create its Build Pipeline. You can also make a GitHub commit and return to your applications page to check the status of your commit.

.. Add integration test Pipeline to test all the components

+
NOTE: For your application, you can define one or more integration tests. For more information, see xref:concepts/testing_applications/con_test-overview.adoc#_integration_service_tests[integration tests]

.. Select or create an environment to run all the components

+
+
NOTE: Site Reliability Engineering (SRE) administrators create a `static` or `managed environment`. For more information, see xref:concepts/release-services/con_release-services-overview.adoc[release services].


.. Optional: Review the status of the first build
.. Optional: Customize Build Pipeline

== Additional resources
* xref:getting-started/build_service.adoc[Build Pipeline customization]
* xref:getting-started/component_deployment_lifecycle.adoc[Component deployment lifecycle]
////
