= Permissions and roles

As a workspace owner, you can https://placeholder.com[invite] one or more collaborators to your workspace by adding their user ID, such as an external SSO ID. After https://placeholder.com[adding a user to a workspace], you assign them a specific role that determines the actions they can take in a workspace.

The roles available for a workspace, from least access to most access, are:

* *Contributor*: Ideal for users who actively push to your workspace.

* *Maintainer*: Ideal for users who need to manage the workspace without access to sensitive actions like managing security or deleting a workspace.

* *Owner*: Ideal for users who need full access to the workspace, including sensitive and destructive actions like managing security or deleting a workspace.

NOTE: By default, the role for newly invited collaborators is *Contributor* but you can upgrade it to *Maintainer* or *Owner*.

== Permissions for each role

The role assigned to a user determines the permissions they have within a workspace, with the Owner role assigning all permissions.


|===
|Permissions for |Action |Contributor |Maintainer |Owner

.4+|Workspace
|View
^|✔️
^|✔️
^|✔️

|Create
|
|
|
|Update

|
|
|
|Delete
|

|
|
.4+|Applications
|View
^|✔️

^|✔️
^|✔️
|Create
|
^|✔️

^|✔️
|Update
|
^|✔️
^|✔️

|Delete
|
|
^|✔️
.4+|Component

|View
^|✔️
^|✔️
^|✔️
|Create

|
^|✔️
^|✔️
|Update
|

^|✔️
^|✔️
|
|
|

^|✔️
.4+|Environment
|View
^|✔️
^|✔️

^|✔️
|Create
|
|
^|✔️

|Update
|
|
^|✔️
|Delete

|
|
^|✔️
.4+|IntegrationTestScenario
|View

^|✔️
^|✔️
^|✔️
|Create
|

^|✔️
^|✔️
|Update
|
^|✔️

^|✔️
|Delete
|
^|✔️
^|✔️

.4+|EnterpriseContract
|View
^|✔️
^|✔️
^|✔️

|Create
|
|
^|✔️
|Update

|
|
^|✔️
|Delete
|

|
^|✔️
.4+|ReleaseStrategy
|View
^|✔️

^|✔️
^|✔️
|Create
|
|

^|✔️
|Update
|
|
^|✔️

|Delete
|
|
^|✔️
.4+|ReleasePlanAdmission

|View
^|✔️
^|✔️
^|✔️
|Create

|
^|✔️
^|✔️
|Update
|

^|✔️
^|✔️
|Delete
|
^|✔️

^|✔️
.4+|User
|View
^|✔️
^|✔️

^|✔️
|Create
|
^|✔️
^|✔️

|Update
|
^|✔️
^|✔️
|Delete

|
^|✔️
^|✔️
.4+|User Group
|View

^|✔️
^|✔️
^|✔️
|Create
|

|
^|✔️
|Update
|
^|✔️

^|✔️
|Delete
|
^|✔️
^|✔️

|===

== Additional resources

* https://placeholder.com[Managing members of a project]
