= Permissions and roles

As a workspace owner, you can add a collaborator to your workspace with their username and assign them a specific role that determines the actions they can take in that workspace. The roles available for a workspace, from least to most access, are the following:

* *Contributor*: For users who actively push code to your workspace but who don't need to manage workspace configuration.
* *Maintainer*: For users who need to manage the workspace without access to sensitive actions like managing security.
* *Owner*: For users who need full access to the workspace, including sensitive actions like managing security.

NOTE: By default, the role for newly invited collaborators is *Contributor*, but you can change this.

== Adding a user to your workspace

.Prerequisites

* The user you want to add must have a valid {ProductName} login.

.Procedure

. From the {ProductName} left navigation menu, select **User Access**.
. Under **Grant user access**, click **Grant access**, or click **Actions**, then **Grant access**.
. From the **Grant access to workspace** page, enter the username of the teammate you want to give workspace access to.
. Under **Assign role**, choose one of the following roles for your new workspace user:
* **Contributor**
* **Maintainer**
* **Owner**
. Click **Grant access**.

.Verification
A message displays that reads, "You invited the user `_username_` to collaborate on the `_workspace_name_` workspace."

== Editing user workspace access

. From the {ProductName} left navigation menu, select **User Access**.
. Next to the user whose access you want to edit, click the three vertical dots. 
. Select **Edit access**. 
. In **Assign role**, select the user's new role. 
* To view the permissions for each role, click **Show list**. 
. Click **Save changes**. 

== Permissions for each role

The role assigned to a user determines the permissions they have within a workspace. Users with the **Owner** role can assign permissions. 

NOTE: Only an {ProductName} administrator can delete a workspace.

|===
|Permissions for |Action |Contributor |Maintainer |Owner

.4+|Workspace
|View
^|✔️
^|✔️
^|✔️

|Create
|
|
|
|Update

|
|
|
|Delete
|

|
|
.4+|Applications
|View
^|✔️

^|✔️
^|✔️
|Create
|
^|✔️

^|✔️
|Update
|
^|✔️
^|✔️

|Delete
|
|
^|✔️
.4+|Component

|View
^|✔️
^|✔️
^|✔️
|Create

|
^|✔️
^|✔️
|Update
|

^|✔️
^|✔️
|
|
|

^|✔️
.4+|Environment
|View
^|✔️
^|✔️

^|✔️
|Create
|
|
^|✔️

|Update
|
|
^|✔️
|Delete

|
|
^|✔️
.4+|IntegrationTestScenario
|View

^|✔️
^|✔️
^|✔️
|Create
|

^|✔️
^|✔️
|Update
|
^|✔️

^|✔️
|Delete
|
^|✔️
^|✔️

.4+|EnterpriseContract
|View
^|✔️
^|✔️
^|✔️

|Create
|
|
^|✔️
|Update

|
|
^|✔️
|Delete
|

|
^|✔️
.4+|ReleaseStrategy
|View
^|✔️

^|✔️
^|✔️
|Create
|
|

^|✔️
|Update
|
|
^|✔️

|Delete
|
|
^|✔️
.4+|ReleasePlanAdmission

|View
^|✔️
^|✔️
^|✔️
|Create

|
^|✔️
^|✔️
|Update
|

^|✔️
^|✔️
|Delete
|
^|✔️

^|✔️
.4+|User
|View
^|✔️
^|✔️

^|✔️
|Create
|
^|✔️
^|✔️

|Update
|
^|✔️
^|✔️
|Delete

|
^|✔️
^|✔️
.4+|User Group
|View

^|✔️
^|✔️
^|✔️
|Create
|

|
^|✔️
|Update
|
^|✔️

^|✔️
|Delete
|
^|✔️
^|✔️

|===

