= Overview of {ProductName} enterprise contract

== How {ProductName} enterprise contract helps you

The main goal of the enterprise contract (EC) is to prevent the release of artifacts that are not compliant with the Supply chain Levels for Software Artifacts (xref:glossary/index.adoc[SLSA]) security framework. Organizations can implement their policies by expressing them as criteria for valid artifacts within the EC. Developers then access the EC as an object inside the workspace. As a developer, reference the EC to verify what must be true about your build and how to make your artifacts compliant with your organization's needs and policies. The EC evaluates the policy definitions against the collected provenance data, ensuring that the build process complies with the enterprise policy. Some examples of the EC policy rules include the following use cases:

* Verify the execution of a set of Tekton Tasks. For example, the EC can assert that a certain Tekton Task, which performs anti-virus checks, ran successfully.
* Verify that all used Tekton Tasks match an expected version and origin.
* Verify that an expected signature key properly signed built artifacts.

== How `Pipelines` and {ProductName} enterprise contract works

The EC establishes a valid set of `Tekton Tasks` and `Tekton Pipelines` based on the customer, enterprise, and security needs and standards. Given that a `Tekton Pipeline` is composed of various `Tekton Tasks`, the EC uses `Tekton Chains` to capture the details of a `Tekton Pipeline` execution in a signed SLSA provenance attestation. Users run a `Tekton Pipeline` to build artifacts, like a container image, while `Tekton Chains` automatically generates the corresponding signed SLSA provenance attestation. When applied, the EC verifies that the SLSA provenance attestation conforms to the configured EC policy.

When a `Tekton Pipeline` produces a container image, {ProductName} stores the signed SLSA provenance attestation alongside the container image in the same repository. `Tekton Chains` also signs the container image, and {ProductName} stores this signature in the same location. The EC ensures the existence and accuracy of both the image signature and the signed SLSA provenance attestation.

== Additional resources

To learn more about {ProductName} EC, see the following pages:

* Enterprise Contract Policies
* Enterprise Contract CLI

To learn about other {ProductName} streams that help you with your containerized development needs, see the following pages:

* xref:concepts/testing_applications/index.adoc[Application testing]
* xref:concepts/release-services/con_release-services-overview.adoc[Release strategy]
* xref:concepts/pipelines/index.adoc[Pipelines]
