= RenovateBot

RenovateBot is a service that detects dependencies in your build pipeline and then creates updates for those dependencies. Your build pipeline is composed of Tekton xref:glossary/index.adoc[tasks]. These tasks come from Tekton bundles which are Open Container Initiative (OCI) artifacts. Your build pipeline references these Tekton bundles. 

RenovateBot monitors Tekton bundle references and makes sure that they're up to date. When new versions of the Tekton bundles are available, RenovateBot creates a pull request with the updated references. This gives you time to review, change, and incorporate the new bundles.

== Authentication and authorization
To create pull requests in target source code repositories Renovate bot has to have proper credentials.

 * GitHub Application - Requires `Red Hat Konflux` GitHub App to be installed in source code reposiotry.

 * GiLab. Create a link:https://docs.renovatebot.com/modules/platform/gitlab/#authentication[Personal Access Token] for the bot account.  Add PAT using link:https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/configuring-builds/proc_creating-secrets-for-your-builds/[
Creating secrets for your builds]

NOTE: The secret has to have such labels:
 `appstudio.redhat.com/credentials` = `scm`, `appstudio.redhat.com/scm.host`=`gitlab.myhost.com`
