= Creating secrets for your builds 

When you build your application, create secrets to ensure the `sast_snyk_task` works. The `sast_snyk_task` analyzes your source code to find vulnerabilities. The `sast_synk_task` secret defines parameters for your build pipeline. Add these `sast_snyk_task` secrets to your build pipeline to ultimately help build and deploy your application. 

.Procedure 

. In {ProductName}, from the left navigation menu, select **Secrets**.
. From the **Secrets** page, click **Add secret**.
. From the **Add secret** page, choose what stage of your application's development you want to create a secret for: **Build** or **Deployment**.
. Select a secret type:
    * **Key/value secret**
    * **Image pull secret**
    * **Source secret**
. For **Secret name**, enter a unique name for your secret.
. Under **Key/value secret**, expand **Key/value 1**, then enter a key.
. For **Upload the file with value for your key or paste its contents**, do one of the following:
    * Click **Upload** to browse to, select, and upload the file that contains your key value.
    * Drag the file that contains your key value into the space under **Upload**.
    * Paste the contents of the file that contains your key value into the space under **Upload**.
  Click **Clear** to remove the contents of the space under **Upload**.
. Optional: Click **Add another key/value**.
. Optional: Under **Labels**, add a label to tag or provide more context for your secret.
. Click **Add secret**.