= Overview of {ProductName} tests

You can ensure that your applications are stable, secure, compliant, and mutually compatible by implementing tests for {ProductName} to run on their components. There are currently 3 types of tests in {ProductName}:

* Surface-level tests
* Product security tests
* Integration tests

The following sections explain each of these test types in greater detail.

== Surface-level tests

Surface-level tests in {ProductName} ensure the stability of the application, the build pipeline, its components, and the environment in which it is being tested. The surface-level tests used in {ProductName} are executed in the form of Tekton xref:glossary/index.adoc#task[tasks]. The utility used for validating container information is link:https://www.conftest.dev/[conftest]. A full listing of {ProductName} surface-level tests is available in this document: xref:how-to-guides/testing_applications/surface-level_tests.adoc[Surface-level tests].

For {ProductName} to perform our predefined surface-level tests on a given component, you must xref:how-to-guides/configuring-builds/proc_upgrade_build_pipeline.adoc[upgrade its build pipeline].

== Product security tests

Product security tests in {ProductName} ensure a product is secure and keep your image, application, and build pipeline up to date. Product Security tests include:

* Vulnerability scanning via Clair
* Anti-virus scanning via ClamAV
* Code scanning via SAST tools

For {ProductName} to perform our predefined product security tests on a given component, you also must xref:how-to-guides/configuring-builds/proc_upgrade_build_pipeline.adoc[upgrade its build pipeline].

== Integration tests

Integration tests ensure that all build components are able to work together at the same time. You can xref:how-to-guides/testing_applications/proc_adding_an_integration_test.adoc[add an integration test], simply by giving {ProductName} the address to a GitHub repo, and the path within that repo to the `.yaml` file that defines the test. See the xref:how-to-guides/testing_applications/proc_creating_custom_test.adoc[create a custom integration test] guide for help on creating your own tekton test pipelines.

{ProductName} runs integration tests after it successfully builds the components of an application. As part of the build process, {ProductName} creates an image for each component and stores them in a Quay.io repository. Images of all the components are then compiled into a snapshot of the application. {ProductName} tests the snapshot against user-defined IntegrationTestScenarios, which, again, refer to a GitHub repository. 


