= Overview of {ProductName} tests

== How {ProductName} testing helps you

{ProductName} has multiple components, one of which is the Test component. The Test component works throughout the pipeline process to ensure your application and its components comply with basic tests, like surface-level, security, or tests you add to the application. The Test component ensures all application components work in congruence with integration testing. Furthermore, administrator defined Enterprise Contract (EC) uses the information provided by the Test component to ensure your application complies with organizational and legal standards. For both component and integration testing, you can create your own tests to ensure your application meets your standards and needs.

== Test types

=== Component tests

There are currently 3 types of image tests in {ProductName}.

* Surface-level Tests
* Product Security Tests
* Custom Tests.

By default, {ProductName} performs Surface-level and Product Security tests. You specifically create the Custom tests for your application.

==== Surface-level tests

Surface-level tests in {ProductName} ensure the stability of the application, the build pipeline, its components, and the environment in which it is being tested. The surface-level tests used in {ProductName} are executed in the form of link:https://tekton.dev/docs/pipelines/tasks/#overview[Tekton tasks]. The utility used for validating container information is link:https://www.conftest.dev/[conftest]. A full listing of {ProductName} Surface-level tests can be link:https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/testing_applications/surface-level_tests[found here].

==== Product Security tests

Product Security tests in {ProductName} ensure a product is secure and keep your image, application, and build pipeline up to date. Product Security tests include:

* Vulnerability scanning via Clair
* Anti Virus Scanning via ClamAV
* Code scanning via SAST tools

These tests can be made mandatory as part of the link:https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/proc_managing-compliance-with-the-enterprise-contract[Enterprise Contract]
// The link used to point to concepts/release-services/con_release-services-overview which is no longer available. A new link probably doesn't make sense because the linked doc doesn't mention prodsec tests listed above.

==== Custom tests

Custom tests in {ProductName} are tests that users and administrators create. To add a custom test to an individual component of an application, customize its build pipeline to include the test as another tekton task. Or, to add a test that runs on all components of an application, create a custom integration test.

//Add two xrefs where appropriate in here ^^

=== Integration tests

Integration tests ensure that all build components are able to work together at the same time. {ProductName} runs integration tests after it successfully builds the components of an application. As part of the build process, {ProductName} creates an image for each component and stores them in a Quay.io repository. Images of all the components are then compiled into a Snapshot of the application. {ProductName} tests the Snapshot against user-defined IntegrationTestScenarios, which refer to a GitHub repository. If all integration tests pass, a Release resource is created for each ReleasePlan. The Release resource notifies the https://red-hat-stone-soup.pages.redhat.com/stonesoup-documentation/concepts/release-services/con_release-services-overview.html[Release service] that the application is ready to be promoted to the next environment.

== Additional resources

To learn about other {ProductName} components that help you with your containerized development needs, see:

* https://red-hat-stone-soup.pages.redhat.com/stonesoup-documentation/concepts/release-services/con_release-services-overview.html[Release Service]
* https://red-hat-stone-soup.pages.redhat.com/stonesoup-documentation/concepts/enterprise-contract/con_enterprise-contract-overview.html[Enterprise Contract]
* https://red-hat-stone-soup.pages.redhat.com/stonesoup-documentation/concepts/pipelines/index.html[Pipeline Services]
