= Important notices about the privacy of your data 

== Publication notification for GitHub and Quay 

As a user, you have the right to understand where and how you enter personal and sensitive data, and when your data gets published to GitHub or Quay. 

== Data in Quay is public 

If you use a public GitHub repository as a component’s source, {ProductName} publishes the container image it builds to a public Quay repository. 

*Note:* There is no functionality to use a private Quay repository. The artifacts {ProductName} builds are public and visible to anyone who is viewing the Quay repository. 

== Data in GitHub repositories is public

When you create an application, {ProductName} stores the link to your GitHub repository, branch, and folder in a GitOps repository managed by {ProductName}. {ProductName} uses that link when it pulls code from your GitHub repository. If you use a personal repo or personal fork from a public project, these Github repository URLs contain your personal Git username. 

*Note:* There is no functionality to store the application configuration in a private GitOps repository. The artifacts created by {ProductName} are public and visible to anyone who is viewing the GitOps repository.

== Secrets for sensitive data are available

With {ProductName}, you can use build and deployment secrets to store sensitive data such as your credentials, API and encryption keys, access tokens, and more. Using secrets helps to secure your environments. We store secrets using AWS Secrets Manager.

*Note:* Use secrets to store sensitive data. Do not enter any sensitive data in environment variables because App Studio stores such variables in a public GitOps repository.

To create secrets, see the link:https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/configuring-builds/proc_creating-secrets-for-your-builds[Creating secrets for your builds] guide.

// TODO add more secrets links when published