= Environments

Environments are standalone pieces of infrastructure that you can use to develop, test, and release your code to production. You can create the following two types of environments in {ProductName}:

* Static

* Managed

Additionally, the system dynamically creates and manages a third type of temporary environment called an *Ephemeral environment*. Here, {ProductName} runs each integration scenario and then removes the environment after completing the build pipeline.

== Static environment

In a static environment, you can safely deploy and test your code (either manually or automatically) in your workspace without breaking published applications in production. 

A static environment is available for every application in a workspace, but you can run only one instance of each application in a static environment. Because of this, when you deploy a new version of an application, {ProductName} replaces the version in your static environment too.

== Managed environment

Managed environments are user-facing workspaces where you link your applications to deploy them to production. This environment is managed by your managed environment team; for example, by service reliability engineers (SREs).

NOTE: You can release an application to production only after it has passed the Enterprise contract policy checks.
