= {ProductName}
:toc: left
:toclevels: 1
:icons: font
:numbered:
:source-highlighter: highlightjs

Welcome to the {ProductName} documentation!

== Why use {ProductName}?

You can use {ProductName} to enable continuous integration and continuous development (CI/CD) for your applications in a matter of minutes. You can also use {ProductName} to secure your software supply chain. With {ProductName}, you can reach link:https://slsa.dev/spec/v0.1/levels#summary-of-levels[SLSA level 3] security standards. And you can customize how {ProductName} builds, tests, and deploys containerized applications.  

== Important notices about the privacy of your data 

=== Publication notification for GitHub and Quay 

As a user, you have the right to understand where and how you enter personal and sensitive data, and when your data gets published to GitHub or Quay. 

=== Data in Quay is public 

If you use a public GitHub repository as a component’s source, {ProductName} publishes the container image it builds to a public Quay repository. 

*Note:* There is no functionality to use a private Quay repository. The artifacts {ProductName} builds are public and visible to anyone who is viewing the Quay repository. 

=== Data in GitHub repositories is public

When you create an application, {ProductName} stores the link to your GitHub repository, branch, and folder in a GitOps repository managed by {ProductName}. {ProductName} uses that link when it pulls code from your GitHub repository. If you use a personal repo or personal fork from a public project, these Github repository URLs contain your personal Git username. 

*Note:* There is no functionality to store the application configuration in a private GitOps repository. The artifacts created by {ProductName} are public and visible to anyone who is viewing the GitOps repository.

=== Data in deployment variables is public 

Developers often use deployment variables, also called environment variables, to store runtime configurations. These variables could contain sensitive data, such as database connections or credential information.

*Note:* There is no functionality to secure sensitive data within a deployment variable. {ProductName} stores deployment variables in a public GitOps repository. Therefore, do not enter any sensitive data in deployment variables at all. 

== Using these documents
To learn more and to get started with {ProductName}, see the following sections: 

xref:getting-started/index.adoc[Getting started]:: Get started with {ProductName}.
[]
xref:how-to-guides/index.adoc[*How-to guides*]:: Put {ProductName} to work for you.
[]
xref:concepts/index.adoc[*Concepts*]:: Learn about technical and conceptual information.
[]
xref:glossary/index.adoc[*Glossary*]:: View a list of relevant terms and their definitions. 
[]
xref:contribute/index.adoc[*Contribute to documentation*]:: View guidelines for contributing.
[]
xref:support/index.adoc[*Support*]:: Join us on Slack, email us, or raise an issue.
