= {ProductName} release services 

{ProductName} has four components, and one of those is the release service. The {ProductName} release service helps site reliability engineering (SRE) administrators to manage a managed workspace. Inside a managed workspace, the {ProductName} release service relies on a release strategy to define the release pipeline that first validates the application snapshot--the content of your application--against the enterprise contract, and then releases that content.

== Managed workspaces 

If you want to deploy your application into the custody of a supporting team like SREs, that team creates a managed workspace based on your original development workspace. The SREs use the release plan in the original workspace and the release plan admission in the managed workspace to define the relationship between the two workspaces. The release plan includes the following pieces of data:

. application name 
. remote workspace name

The `release plan admission` includes the following pieces of data:

. application name 
. origin workspace name
. release strategy
. target environment

With this data, the release plan and release plan admission connect the workspaces to ensure consistency, and delegate the releases between them to maintain maximum productivity. 

== Release strategy and pipeline 

Inside a managed workspace, SREs rely on the release strategy to deploy your application. The release custom resource provides the snapshot and the release plan. The snapshot includes everything you want to deploy in your application. The release plan connects the release plan admission in the managed workspace. This is what identifies where to deploy the application and what strategy is being followed. The release strategy contains the release pipeline. The pipeline defines the process for validating the snapshot against the enterprise contract to meet security standards and to release your content.

== Additional resources 

To learn about other {ProductName} components that can help you with containerized development, see the following:

* xref:how-to-guides/testing_applications/con_test-overview.adoc[Testing applications] 
* xref:concepts/enterprise-contract/con_enterprise-contract-overview.adoc[Enterprise contract] 
* xref:concepts/pipelines/index.adoc[Pipelines]
