= Creating a team workspace

When you first login to {ProductName}, you are granted a personal workspace dedicated to your username. But, sometimes, you want a workspace to organize work for your *team*, not just yourself.

Because workspace creation is tied to SSO login identities in {ProductName}, in order to create a team workspace you need to create and login as an SSO identity that bears the same name as the team

Key steps include:

* **Create an SSO account for the team:** A prerequisite, giving {ProductName} the information it needs to create the team workspace.
* **Login to {ProductName} and join the waitlist:** Triggering the creation of the workspace.
* **Add team members to the shared workspace:** Allowing the team to get down to work.

.**Prerequisite**

* You are link:https://www.redhat.com/wapps/ugc/sso/logout[logged out] of the {ProductName} SSO provider.

.**Procedure**

. As in xref:getting-started/get-started.adoc[Getting started], visit https://console.redhat.com/preview/hac/application-pipeline[{ProductName}].
. When prompted to login, select the link to register for a new account.
. Follow the account creation steps.

NOTE: For the login name, choose a name that reflects the identity of your team. This will become your team's workspace name.

NOTE: For the email address, choose an address that you can access. Use a team mailing list, or a modified form of your personal email like `<your_username>+<team_name>@<domain>.com`.

. Once the account is created, use it to log in to https://console.redhat.com/preview/hac/application-pipeline[{ProductName}].
. As in xref:getting-started/get-started.adoc[Getting started], join the waitlist.
. Once approved, visit the link:https://console.redhat.com/preview/application-pipeline/access[User Access] section of the user interface to grant the xref:getting-started/roles_permissions.adoc[owner role] to your normal user identity.
. link:https://www.redhat.com/wapps/ugc/sso/logout[Log out] and log back in as your normal user identity, and confirm you have access to the team workspace via the workspace switcher.

NOTE: Once your normal user identity is granted admin, you should be able to add and manage other team members' access as your normal user identity by using the *User Access* section of the user interface.
