# Copyright 2022 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License..
#
# SPDX-License-Identifier: Apache-2.0

---
name: Check pull request

'on':
  pull_request:
    branches:
      - main

jobs:
  antora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.npm
          key: docs-${{ hashFiles('package-lock.json') }}
          restore-keys: docs-

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Install Dependencies
        run: npm install

      - name: Generate website
        run: npm ci && npm run build

      - name: Store pull request data
        run: |
          mkdir pull_request
          echo ${{ github.event.pull_request.number }} > ./pull_request/number

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: |
            public
            pull_request
